name: hvac_unit_converter
description: HVAC unit converter for Web, Android, and iOS.
publish_to: 'none'
version: 0.13.0+13

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
